# Deployment do Postgresl
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - name: postgre
          image: postgres:14.3
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: "#DEVOP$_PRO"
            - name: POSTGRES_USER
              value: "kubedevnew"
            - name: POSTGRES_DB
              value: "kubedevnew"

---
# Service do Postgresl
apiVersion: v1 
kind: Service 
metadata:
  name: postgre
spec:
  selector:
    app: postgre
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  
---

# Deployment do Postgresl
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubenews
  template:
    metadata:
      labels:
        app: kubenews
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: kubenews
          image: juangaray22/kube-news:v1
          env:
          - name: DB_DATABASE
            value: "kubedevnew"
          - name: DB_USERNAME
            value: "kubedevnew"
          - name: DB_PASSWORD
            value: "#DEVOP$_PRO"
          - name: DB_HOST
            value: "postgre"
---

# Service da Aplicacao
apiVersion: v1 
kind: Service 
metadata:
  name: kube-news
spec:
  selector:
    app: kubenews
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30000
  type: LoadBalancer